Connect user to chat to increase watchtime
Tkd-Alex/Twitch-Channel-Points-Miner-v2 pull request #47
Opened 2021-02-03 17:51 UTC by anoviel

add irc chat client
list user as viewer in selected chat
viewtime increases while connected 

Referenced issue
https://github.com/gottagofaster236/Twitch-Channel-Points-Miner/issues/16

2021-02-03 20:38 UTC, Tkd-Alex commented
I think there are a lot of things that should be changed. 
I'll start a review asap!

2021-02-03 20:45 UTC, Tkd-Alex requested changes

2021-02-03 20:45 UTC, Tkd-Alex commented on TwitchChannelPointsMiner/TwitchChannelPointsMiner.py
> +            if streamer is not None:
We don't need `if streamer is not None:`
Why a streamer should be None?

2021-02-03 20:45 UTC, Tkd-Alex commented on TwitchChannelPointsMiner/classes/entities/Chat.py
> +        irc.bot.SingleServerIRCBot.__init__(
- `server = "irc.chat.twitch.tv"`
- `port = 6667`

Should be moved in `constants/twitch.py`

2021-02-03 20:45 UTC, Tkd-Alex commented on TwitchChannelPointsMiner/classes/TwitchChat.py
> +
We don't need the class `ChatSettings`
It's only `self.username` and `self.token`? 

We have already this value.

2021-02-03 20:45 UTC, Tkd-Alex commented on TwitchChannelPointsMiner/classes/entities/Streamer.py
> +        chat_client: ChatSettings = None,
as already said we don't need: `ChatSettings`

2021-02-03 20:48 UTC, Tkd-Alex commented
If you want you can take a look of this https://pypi.org/project/python-twitch-irc/

2021-02-03 20:50 UTC, Tkd-Alex requested changes

2021-02-03 20:50 UTC, Tkd-Alex commented on TwitchChannelPointsMiner/classes/TwitchChat.py
> +class TwitchChat(Process):
It's a long running-job with lower I/O.
We should extend a `Thread` instead of `Process`

2021-02-03 23:11 UTC, anoviel commented
I had some issues getting pre-commit up and running on windows 😅
Thanks for the feedback, I will improve things as soon as possible :)

2021-02-03 23:16 UTC, Tkd-Alex commented
> I had some issues getting pre-commit up and running on windows 
> Thanks for the feedback, I will improve things as soon as possible :)

If you have a problem with pre-commit run the following commands:
- `pre-commit uninstall`
- `pip install pyflakes, black, isort`
- `isort TwitchChannelPointsMiner/`
- `black TwitchChannelPointsMiner/`
- `flake8 TwitchChannelPointsMiner/`\

So you can check the code manually :smiley:

2021-02-17 10:31 UTC, Tkd-Alex commented
@anoviel Have you the time for work on it? or do you prefer that I complete the review?

2021-03-09 22:48 UTC, Tkd-Alex approved these changes

2021-03-09 23:51 UTC, Tkd-Alex commented
Hi :) After a long time I've updated this PR.
If someone wants to try :smile_cat:

2021-03-10 00:06 UTC, kelukelol commented
> Hi :) After a long time I've updated this PR.
> If someone wants to try 😸

Going to test it for an hour or so. I will let you know if something comes up :)
![image](https://user-images.githubusercontent.com/76735490/110555384-2f3a2b80-8145-11eb-9516-5a22c777c160.png)

2021-03-10 01:44 UTC, kelukelol commented
`10/03/21 03:42:17 - INFO - [__print_report]: Duration 1:21:55.017667` works just fine without any issues appearing.

2021-03-10 08:44 UTC, Tkd-Alex commented
The script workings as well with on-line/offline events? Because currently I don't know what happened when a streamer go offline and then online again

2021-03-10 09:11 UTC, kelukelol commented
I am not sure about that too. I have not seen this happen in 2 hours just looking at the script work :/

2021-03-10 14:31 UTC, PureFallen commented
Someone could also just open a Private Window/Incognito Tab and check in the Twitch Chat´s Memberlist, if the Accountname is listed. If so, the feature works as intended. It even works for more than 2 streamers, given that the viewlimit does not apply to Twitch Chat. Glad that this was considered in the PR.

However, the new feature draws attention to 2 things:

- Dealing with channels that don't have Channel Points active
It might be attractive for someone that migrates from another solutions to this software to join the IRC from channels that don't support Channel Points, regardless of the intentional purpose of the software. The reasons for that can vary, like the Watchtime example @anoviel mentioned before, farming alternative currencies such as StreamElements/StreamHeroes (which are measured by time active in chat), qualifying for drops or subscription gifts (which select random people that were in the chatbox in the last x hours) or more.

People could put those streams simply on the very bottom of the list, but assuming every other stream in the list is offline, they might up creating load on script and network for farming Viewtime on a stream it is not worth it... unless there is a way to detect that a channel doesn't support Channel Points?
An alternative approach would be to provide a setting `irc_only` (default: false) for the Streamer Settings, automatically making them treat with lowest priority and completely ignored for the requests related for Channel Points, Predictions.... stuff like that.

- Dealing with channels that reward people for being in the chatbox, while the Stream if offline
This sounds really odd in the first moment, but there are Streamer which are actually checking and rewarding people for the time they spend in Chatbox regardless of the Stream's Online State. The reasons for that can vary over wanting to maintain an active chat, even if offline (to make the impression of a healthy/active community) or sometimes even easier: using a selfcoded bot and messing up the Online-Check for it.

Once again there would probably be a setting required to join Streamer´s IRC regardless of their Online State, but at this point it might be even better for the readability and usability to have a seperate list of Streamers in the run.py where people can put streams that are exclusive for IRC usage and configure the behaviour with Offline Streams there, before the "StreamerSettings" in `twitch_miner.mine` grow even longer...

2021-03-10 14:38 UTC, Yishaqel commented
The latest log (which has been running since last night) takes 100MB because it is saving the messages in the IRC channels. I don't think I can share it but I have received a couple of errors today.

2021-03-10 14:48 UTC, Tkd-Alex commented
> The latest log (which has been running since last night) takes 100MB because it is saving the messages in the IRC channels. I don't think I can share it but I have received a couple of errors today.

They are all messages from irc chat. 
I'll remove asap because we don't need them.

2021-03-10 15:12 UTC, kelukelol commented
Keep getting an issue every time the bot leaves the IRC chat.
![image](https://user-images.githubusercontent.com/76735490/110650963-af06db00-81c3-11eb-8e5b-ea23c187fa39.png) 
I bet this has something to do with me having Windows :/

2021-03-10 15:40 UTC, Tkd-Alex commented
:cry: :cry: :cry: 

On Linux for the moment no problem when the streamer goes offline.
![image](https://user-images.githubusercontent.com/14061593/110655425-559cad00-81bf-11eb-9018-d25dd0f32a40.png)

2021-03-10 15:50 UTC, Tkd-Alex commented
Are you able to edit add a time sleep here?
https://github.com/anoviel/Twitch-Channel-Points-Miner-v2/blob/46918fda9b181af2fa5243587cdf9256b4fcc129/TwitchChannelPointsMiner/classes/entities/Chat.py#L26-L27

```python
import time
....
code
code
....
self.reactor.process_once(timeout=0.2)
time.sleep(0.01)
```

We could also surround with `try except` and see if something change.

2021-03-10 15:54 UTC, kelukelol commented
Bruh, it just fixed itself without me making any changes.

2021-03-10 15:56 UTC, Tkd-Alex commented
Awesome! :rofl: 
Anyway I think I'll do this changes just for prevent future errors.

2021-03-10 16:40 UTC, PureFallen commented
> 
> > unless there is a way to detect that a channel doesn't support Channel Points?
> 
> I think yes, should be a way. If you can provide a streamer without channel points maybe I can't find a way.
> 

Not want to advertise Streamers, but you could take a look into Twitch's "Slot" Category. Streamer which exclusively stream Slots don't meet the requirements for Affiliation/Partnership and therefore can't enable Channel Points.
You will find someone really quickly there^^

> uhm agree, your message make sense. I got your points.
> Currently, I think I'll merge this PR asap and then create a new branch with your idea and proposals. Because seems that @anoviel haven't free time to work on It and for me, It's a little uncomfortable to work on another user's repository. We could consider [#47 (comment)](https://github.com/Tkd-Alex/Twitch-Channel-Points-Miner-v2/pull/47#issuecomment-795499841) as improvements.

Oh, sure. I am just extremly unexperienced with Github in general. Should learn that at some point. Limiting it to theorycrafting most of the time for now. I really appreciate that.

2021-03-10 21:26 UTC, Tkd-Alex commented
![image](https://user-images.githubusercontent.com/14061593/110699951-ae843980-81ef-11eb-945f-afe797b9e8be.png)

Here another error :cry: 
I'm currently working on this.

2021-03-12 13:57 UTC, Tkd-Alex commented
Seems to be stable.
I'll merge asap, anyone has founded problems? 

@PureFallen after the merge please open a new issue. You can easily do a Copy & Paste or open new issue directly via GitHub.

![image](https://user-images.githubusercontent.com/14061593/110949774-4b0b2080-8343-11eb-8a60-bb9ee5628c85.png)

2021-03-12 14:12 UTC, kelukelol commented
> Seems to be stable.
> I'll merge asap, anyone has founded problems?
> 
> @PureFallen after the merge please open a new issue. You can easily do a Copy & Paste or open new issue directly via GitHub.
> 
> ![image](https://user-images.githubusercontent.com/14061593/110949774-4b0b2080-8343-11eb-8a60-bb9ee5628c85.png)

Left the script running over this night. After reading logs, no issues have been found. (Despite this issue https://github.com/Tkd-Alex/Twitch-Channel-Points-Miner-v2/pull/47#issuecomment-795581741 but it fixed itself. )

2021-03-12 22:04 UTC, merged